server:
  port: 8080
spring:
  datasource:
    initialize: true
    url: jdbc:mysql://localhost:3306/qrtz?useUnicode=true&characterEncoding=utf8
    username: demo
    password: changeme
    driver-class-name: com.mysql.jdbc.Driver

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  format_sql: true
  hbm2ddl.auto: update

quartz.enabled: true
